import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies=[("finance","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="TopUp",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("operation_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("amount_minor",models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),("status",models.CharField(choices=[("CONFIRMED","Confirmada")],default="CONFIRMED",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="topups",to=settings.AUTH_USER_MODEL))],options={"verbose_name":"recarga simulada","verbose_name_plural":"recargas simuladas"}),
        migrations.CreateModel(name="Withdrawal",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("operation_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("amount_minor",models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),("status",models.CharField(choices=[("CONFIRMED","Confirmada")],default="CONFIRMED",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="withdrawals",to=settings.AUTH_USER_MODEL))],options={"verbose_name":"retiro simulado","verbose_name_plural":"retiros simulados"}),
        migrations.CreateModel(name="VirtualToRealConversion",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("operation_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("amount_minor",models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),("status",models.CharField(choices=[("CONFIRMED","Confirmada")],default="CONFIRMED",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("fee_virtual_minor",models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),("net_real_minor",models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),("user",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="virtualtorealconversions",to=settings.AUTH_USER_MODEL))],options={"verbose_name":"conversión virtual a real","verbose_name_plural":"conversiones virtual a real"}),
        migrations.CreateModel(name="VirtualTransfer",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("operation_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("amount_minor",models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),("status",models.CharField(choices=[("CONFIRMED","Confirmada")],default="CONFIRMED",max_length=20)),("created_at",models.DateTimeField(auto_now_add=True)),("recipient",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="virtual_transfers_received",to=settings.AUTH_USER_MODEL)),("user",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="virtualtransfers",to=settings.AUTH_USER_MODEL))],options={"verbose_name":"transferencia virtual","verbose_name_plural":"transferencias virtuales"}),
        migrations.AddConstraint(model_name="virtualtransfer",constraint=models.CheckConstraint(condition=models.Q(("user",models.F("recipient")),_negated=True),name="fin_transfer_sender_ne_recipient")),
    ]
